Add `IMPORT/EXPORT DATABASE`
kuzudb/kuzu-docs pull request #125
Opened 2024-04-15 19:38 UTC by hououou

2024-04-15 19:43 UTC, hououou commented
@prrao87 I do not how to add page links. Could you please help me link the  `import_export_database.md` in the correct place? ( I think it may be linked in `Cypher manual` directory.)

2024-04-15 20:37 UTC, prrao87 commented
Hi @hououou, you can link it without the `.md` extension and the relative path (just the file name). That should work.

2024-04-15 20:40 UTC, prrao87 requested changes

2024-04-15 20:40 UTC, prrao87 commented on src/content/docs/cypher/import_export_db.md
> +Kùzu allows you to import/export database using query statements.
Can you add a line here at the start why you may want to import/export a database? (Something along the lines of if you need to migrate the contents of an existing database to a different version of Kùzu). Also, maybe we should mention the cases where the import/export may not work (e.g., backward compatibility is not guaranteed).

2024-04-15 20:40 UTC, prrao87 commented on src/content/docs/cypher/import_export_db.md
> +## EXPORT DATABASE
Headers should be title case (Only first letter is capitalized) in this case, `## Export database`

2024-04-15 20:40 UTC, prrao87 commented on src/content/docs/cypher/import_export_db.md
> +## IMPORT DATABASE
Headers should be title case (Only first letter is capitalized) in this case, `## Import database`

2024-04-18 14:51 UTC, prrao87 approved these changes
I made the required updates for clarity and added the links 👍🏽. Will merge once we make the 0.4.0 release.

2024-04-18 21:10 UTC, merged